nyaosorg/nyagos

completion/completion.go

パス補完時に、`/`はあるが`\`ない場合
入力済みの`/`も`\`に置換され補完されます。
例えば、
```
$ cd /Win<タブ>
```
で補完した場合、補完結果が
```
$ cd \Windows\
```
となります。
期待動作としては、最初に`/`があるので
補完結果は
```
$ cd /Windows/
```
ではないでしょうか？

Fix path completion behavior with SLASH but no BACKSLASH.

---

commands/set.go
main/lua_cmd.go

環境変数の削除する方法が提供されていなかったので、実装してみました。
`$ unset name` としようとしたのですが、Windows のコマンドプロンプトでは、`$ set name=` とすると削除されるようなので、そのように実装しました。
```sh
$ set name= # これで消える
$ lua_e "nyagos.setenv('name', '')" # これでも消える
```
実装方法に問題などあれば、修正します。よろしくお願いいたします。

Unix コマンドの unset に対応する操作を追加

---

main/prompt.go

プロンプトの日付の month が +1 されて進んでいました。
また、他では year,month,day変数は使われていないようなので go言語の Format() 関数に変更してみました。

Fixed wrong month in prompt 'd'.

---

commands/copy.go

`/y` オプションを追加するときにフォルダーへの操作しかテストしてませんでした。

copy/move: fix when destination is not folder

---

conio/readline_isearch.go

Interrupt isearch by Ctrl-C

---

interpreter/parser.go

Windows の[環境変数] [1]には `=` を含められないという制限しかないみたいです。
[1]: https://msdn.microsoft.com/en-us/library/windows/desktop/ms682653(v=vs.85).aspx

Improve environment variable parsing

---

nyagos.d/catalog/subcomplete.lua

#205 support
use this
subcommand completion from git-completion.bash
```:lua
-- in user .nyagos
-- catalog
use "subcomplete"
-- completion 2nd append start
local maincmds = share.maincmds
-- git
local gitsubcommands={}
-- setup
gitsubcommands["bisect"]={"start", "bad", "good", "skip", "reset", "visualize", "replay", "log", "run"}
gitsubcommands["notes"]={"add", "append", "copy", "edit", "list", "prune", "remove", "show"}
gitsubcommands["reflog"]={"show", "delete", "expire"}
gitsubcommands["rerere"]={"clear", "forget", "diff", "remaining", "status", "gc"}
gitsubcommands["stash"]={"save", "list", "show", "apply", "clear", "drop", "pop", "create", "branch"}
gitsubcommands["submodule"]={"add", "status", "init", "deinit", "update", "summary", "foreach", "sync"}
gitsubcommands["svn"]={"init", …
```

add 2nd subcommand completion

---

nyagos.d/catalog/subcomplete.lua

自動補完でユーザー定義関数を設定可能にします
share.maincmds[cmdname]が
nil : 補完なし
table == type():補完リストとして利用
function == type():補完リストtableを返す関数として呼び出し

Add support subcmds as function

---

nyagos.d/catalog/git.lua

関数のshareへの登録と動作の確認をしましたので、修正をpullします。
以下としてaliasで関数補完ができています(coはcheckoutの短縮、mbはmergeの短縮)
```lua:.nyagos
use "git"
-- completion 2nd append start
local maincmds = share.maincmds
-- git
local gitsubcommands={}
-- setup
-- alias
gitsubcommands["co"]=share.git.branch
gitsubcommands["mb"]=share.git.branch
-- build
for key, cmds in pairs(gitsubcommands) do
local gitcommand="git "..key
maincmds[gitcommand]=cmds
end
-- replace
share.maincmds = maincmds
-- completion 2nd append end
```

Fix git branch func registration

---

nyagos.d/aliasandset.lua

4.1.9.2以降で`alias`の定義でエラーが発生していたので修正してみました
```lua
alias { e = 'vim' }
```
```
[string "C:\nyagos-4.1.9_3-amd64\nyagos.d\aliasandset...."]:11: attempt to call a userdata value (local 'f')
```

Fix: aliasandset.lua

---

nyagos.d/catalog/autocd.lua

同名のフォルダとコマンドと存在する際にフォルダが優先されて(例:`~/go`と`go.exe`)
bash等のautocdではコマンドが優先、と挙動が違ったので修正しました

Fix: autocd.lua

---

readline/buffer.go

related https://github.com/mattn/go-colorable/commit/3fa8c76f
上記コミット以降の go-colorable に対応するための修正です。
逆に go-colorable が上記コミットより前の状態でビルドすると、Ctrl-A 等でカーソルを移動した時に意図と逆方向にカーソルが移動します。

fix ANSI escape code for cursor backward

---

mains/complete_lua.go

completion_hook で補完候補をカスタマイズできますが、戻り値として返した配列の順序が保存されないようです。
例えば、
```lua
nyagos.completion_hook = function(c)
-- case-sensitive completion.
local list = {"aa", "ab", "ac", "ad"}
return list
end
```
という completion_hook を指定し、
```bash
> a[TAB]
```
を実行した場合、表示される `aa ab ac ad` の順序が TAB を押すたびに変わります。
Lua での配列は Go の世界に戻った時に map になるので、そこで要素の順序が保証されなくなっているように見えました。
(Go も Lua も初心者なので、変な個所がありましたらご指摘いただけると助かります。)

completion_hook の戻り値の配列の順序が保持されない

---

lua/to.go

Most of `userdata` should not be set to `share` hash.
Let's think of the following example.
```lua
-- Create WScript.Shell.
local ole = nyagos.create_object("WScript.Shell")
-- Launch notepad.exe
-- This will launch notepad.exe successfully.
ole:Run("notepad.exe")
for i=1, 10 do
-- Save ole in share hash.
share.ole = ole
ole = nil
-- The following ensures that ole object is garbage-collected.
-- As a result, ole:__gc is called.
collectgarbage("collect")
-- Retrieve ole from share hash.
ole = share.ole
end
-- The following may fail and cause crash because ole:__gc has been called and 
-- `Data *ole.IDispatch` in capsule_t has already been released.
ole:Run("notepad.exe")
```
In the above example, the second call of `ole:Run` may fail because `ole:__gc` has already been called and `Data` in …

Reject conversion from userdata to Object.

---

lua/lua.go
lua/meta.go
lua/ole/ole.go
lua/stream.go
lua/to.go
mains/lua_cmd.go

The following `sample.lua` sometimes causes panic.
```lua
-- sample.lua
for i = 1, 10000 do
for line in nyagos.lines("sample.lua") do
end
end
```
Run the above script as follows:
```bat
C:\Users\xxx> set GOGC=1
C:\Users\xxx> nyagos.exe
Nihongo Yet Another GOing Shell 4.2.1_0-7-g6412fc0-386 by go1.8.3 & Lua 5.3
(c) 2014-2017 NYAOS.ORG <http://www.nyaos.org>
$ lua_f sample.lua
```
Here is the output of panic.
```
runtime: nelems=1024 nfree=1019 nalloc=5 previous allocCount=4 nfreed=65535
fatal error: sweep increased allocation count
runtime stack:
runtime.throw(0x5a0549, 0x20)
C:/my_program/go/src/runtime/panic.go:596 +0x7c
runtime.(*mspan).sweep(0x9d67e4, 0x300, 0x3f3)
C:/my_program/go/src/runtime/mgcsweep.go:288 +0x694
runtime.sweepone(0x42ab6c) …
```

Keep userdata objects in Golang world to avoid garbage collection.

---

commands/bindkey.go

This patch fixes crash in `cmd_bindkey`.
When `bindkey` is called without any arguments, it causes crash of NYAGOS.
Regards,
Murase

Fix crash in cmd_bindkey.

---

commands/source.go

source で *.bat 等を実行した際の stdout / stderr が表示されないのを、まとめて本体側の stdout に表示する PR です。
（書いてる途中で（もしかして意図的に出してないのでは）と思いましたがとりあえず投げます:bow:）

`source` execute a batch with stdout

---

frame/loadscr.go

多分[ここ](https://github.com/zetamatta/nyagos/blob/master/gopherSh/nyagos.go#L103)で`nil`を返しているためだと思いますが、キャッシュが空になり2回目の起動時から`%HOME%\.nyagos`または`%USERPROFILE\.nyagos`の内容が読み込まれません。`chank != nil` の場合のみ書き込むようにするだけでも良いかと思いますが、既に`0Byte`のキャッシュができている場合の救済策として空の場合はキャッシュを読まないようにしています。

Fix issue that user's .nyagos was not loaded

---

frame/loadscr.go

#305 については早々に対応頂いてありがとうございました。`lua53.dll`版から`Gopher-Lua `版にアップデートした場合、`.nyagos`のキャッシュが読み込めず`%HOME%\.nyagos`または`%USERPROFILE%\.nyagos`の読み込みに失敗します。Luaの実装が変わったことの検出方法が不明で、手で消せば良いやということで、 #305 では対応できなかったのですが、よく考えてみればキャッシュの読み込みに失敗した(キャッシュが無効だった)場合、キャッシュを消してしまって問題ないことに気づきました。その方向で修正してみたのですが、問題なければ取り込んで頂けますか。

Change to delete if .nyagos cache is invalid

---

make.cmd

make.cmd で goversioninfo.exe を生成する際に $GOPATH/bin に goversioninfo.exe をインストールすることは意図してなさそうだったので、go get の -d フラグでダウンロードのみにする PR です。
go get 後に goversioninfo 側で go build したものをコピーしてきてるところから上記のように読んだのですが、そもそも前提が間違っていましたら破棄してください 🙇

no install goversioninfo.exe to $GOPATH/bin

---

mains/io.go

4.3.2_0 から `io.*` が NYAGOS の自前バージョンに置き変えられましたが、`file:read(...)` に以下のような問題があるようです。
- フォーマットを省略した場合、デフォルトで `*l` になるべきところがそうなっていないようです
- フォーマットが `*l` の場合、かつ行が改行で終わっていない場合に何も読み取られないようです
修正してみましたので、問題がなければ取り込んで頂けますか？

Fix Lua's file:read

---

shell/source.go

*.cmd ファイル等を実行した際にnyagosが異常終了するため対応してみました。
例) 以下のファイルを実行するとnyagosが異常終了します。
test.cmd
```cmd
exit /b -1
```
nyagos.dump
```
************ Panic Occurred. ***********
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0x6d5300, 0xc00021c0a0, 0xc0002c3490)
C:/Go/src/runtime/debug/stack.go:24 +0xae
github.com/zetamatta/nyagos/frame.PanicHandler()
C:/home/go/src/github.com/zetamatta/nyagos/frame/misc.go:52 +0x1b4
panic(0x64e2c0, 0x860600)
C:/Go/src/runtime/panic.go:513 +0x1c7
fmt.Fprintf(0x0, 0x0, 0x694b62, 0x1e, 0xc0002c3718, 0x1, 0x1, 0x0, 0x0, 0xc0002c3748)
C:/Go/src/fmt/print.go:189 +0x7e
github.com/zetamatta/nyagos/shell.readEnv(0xc0002c3790, 0x0, 0x0, 0x0, 0x0, 0x42b00a)
C:/home/go/src/github.com/zetamatta/nyagos/shell/source.go:32 …
```

Fix shell.readEnv

---

nyagos.d/catalog/subcomplete.lua

Issue #345 の対応です。
gitのhelp文面が2space indentが3spaceになっています。
これに対応し、今後もフォローするため、複数スペースでチェックするようにしました。
また、その後にある文字列も取得してしまう問題もあったので、gmatchはせず、match時のキャプチャでコマンドを確定させています。
同じ修正としてsvnのスペースも対応しています...が、この変更のありなし関係なくsvnは補完動作しせん。(手元で)
さらに生のサブコマンドを吐くhgも効きません...

fix git completion

---

nyagos.d/catalog/git.lua
nyagos.d/catalog/subcomplete.lua

hubコマンドをサポートするPRです。
* hubコマンドがあれば、hubにも補完が発生+gitの補完にhubの特別コマンド追加
* hubコマンドがあるなら、gitのエイリアスに設定
GITHUB_TOKENを使って、`git issue`とかできます。
自分は環境変数にTOKEN載せたくないので、次のような設定にしましたが。
```lua:dot.nyagos.lua
-- hub command with github token
if nyagos.which("hub.exe") then
nyagos.alias.hub = function(args)
local github_secret = nyagos.eval('gpg --no-verbose --quiet --batch --decrypt --output - ~\\.password-store\\Develop\\Github.gpg 2> nul')
github_secret = github_secret .. "\n" -- lastline append return
local token = ""
local username = ""
for line in github_secret:gmatch("[^\r\n]+") do
if (0 ~= string.len(token)) and (0 == string.len(username)) then
username = line:match("^username:%s+(%S+)")
end
if 0 == string.len(token) then
token = line
end
end
nyagos.env["GITHUB_USER"] = username …
```

completion support hub like git

---

commands/ls_windows.go

`ls -h` オプションが仕様と違ってカンマ区切りになっています。
nyagos 4.4.6_2
https://github.com/zetamatta/nyagos/blob/master/Doc/04-Commands_ja.md#ls--%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3-
>  -h -l 使用時に、人間が読みやすい形式でサイズを表記します (例:1K 234M 2G)
`ls -l` のファイルサイズ出力がカンマ区切りとなっています。
```
[C:/WorksLab/nyagos]
2020-07-05 01:31:10.41>ll
drwx---        0 Jul  5 01:18:45 Doc/
drwx---        0 Jul  5 01:18:45 Etc/
-rw-a--    1,542 Jul  5 01:18:45 LICENSE
-rw-a--      845 Jul  5 01:18:45 _nyagos
drwx---        0 Jul  5 01:18:45 alias/
-rw-a--    1,623 Jul  5 01:18:45 appveyor.yml
```
`humanize.Comma()` が使われていますが、単位表記にするためには `Bytes()` メソッドを使う必要があります。
/nyagos/commands/ls_windows.go:137
```go
if (flag & O_HUMAN) != 0 {
fmt.Fprintf(out, " %*s", width, humanize.Bytes(uint64(status.Size())))
} else {
fmt.Fprintf(out, " %*d", …
```

Fix the file size output of `ls -h` to be displayed in units.

---

nyagos.d/catalog/git.lua

Work below for user `.nyagos`
```lua:.nyagos
-- git
local gitsubcommands=share.git.subcommand
-- git subcommand alias
gitsubcommands["br"]=share.git.branch
share.git.subcommand=gitsubcommands
```
ex
```
$ git br <tab>
```

fix: git subcommand completion for user extendable(like git br <branch>)

---

mains/utf8lua.go
t/utf8offset.lua

I want nyagos to improve the implementation of `utf8.offset`.
Currently, nyagos has `utf8.offset`, but the returned value is different from the one of the original implementation in a certain condition.
For example, `utf8.offset("ab", 3)` returns not `3` but `2`.
This patch fixes the returned value of this kind of corner case.

Improve utf8 offset

---

nyagos.d/catalog/subcomplete.lua

This PR is fix below.
* comment string, position and lack.
* code indent adjust (space 4)
* command check add
At last, why is needed for command check?
When any command do not found, print for every shell starup 
```log
'scoop' is not recognized as an internal or external command,
operable program or batch file.
```
(ex "scoop")

fix: subcomplete.lua some code and comment

---

nyagos.d/catalog/fuzzyfinder.lua

Add catalog module for fuzzyfinder that bind to C_o/C_r/M_H/M_G .
Copy from "peco.lua", but generic module name and settings.
- name is generic
- args add per selecting command
Default settings use "fzf" and preview args.
- git log "git show {hash}"
- (dir item/cd hist "dir {target}" do not perfect work, removed)
When use "peco", set below:
- share.fuzzyfinder = {}
- share.fuzzyfinder.cmd  = "peco"
- share.fuzzyfinder.args = {}
- share.fuzzyfinder.args.dir     = ""
- share.fuzzyfinder.args.cmdhist = ""
- share.fuzzyfinder.args.cdhist  = ""
- share.fuzzyfinder.args.gitlog  = ""
Keep "peco.lua" file, safe current setting code using peco user.
I hope "peco.lua" integrate to "fuzzyfinder.lua".

feat: add fuzzyfinder catalog module

---

nyagos.d/catalog/git.lua

related #413 
follow up / complementary
- Update keyword in Git 2.33.1 at 2021/11/07 from official documents.
- Keyword are sorted alphabetically, next add/remove position keep for simply and diff easy.
- Add keyword support `remote` and `sparse-checkout`.
- Treat comments. 
- Add `TODO` for future update. For git official completion category group supporting and noted in comment.
---
キーワード側メンテが不足してましたね...ということで追加PRです

fix: git subcommand keyword update

---

main.go

**概要**
main.go の go:embed の パス文字列が `etc/version.txt` だとエラーになってしまうので `Etc/version.txt` に修正しました
発生したエラー
```
main.go:15:12: pattern etc/version.txt: no matching files found
```

Fix: go:embed path( etc -> Etc)

---

nyagos.d/catalog/fuzzyfinder.lua
nyagos.d/catalog/fzf.lua
nyagos.d/catalog/peco.lua

このPRでは以下のような統合を行います。
* peco.lua の peco 利用について fuzzyfinder.lua を利用するように変更し、統合
* fuzzyfinder.lua の初期設定を整理(最初にいろいろやっているが、後から壊れた値を share.fuzzyfinder にセットしたときどうしようもないので、その部分を削除)
* fzf 利用を明確に行う fzf.lua を新設
これにより
* fuzzy finder 全般は fuzzyfinder.lua が担う
* peco.lua 利用者は変更なしで挙動変化なし
* fzf を明示的に利用したい人の簡便な方法を提供
* 設定無しで fuzzyfinder.lua を利用していた人も最低限挙動を保証
利用例
example 1. peco を簡単につかう
```lua
use "peco"
```
example 2. fzf を簡単につかう
```lua
use "fzf"
```
example 3.任意のfuzzyfinderを使う(カスタム設定)
ここでは https://github.com/rschmitt/heatseeker を利用する例
peco/fzfでもより詳しく設定したいなら同様に行う
```lua
use "fuzzyfinder"
local hs = {}
hs.cmd          = 'hs.exe'
hs.args         = {}
hs.args.dir     = ''
hs.args.cmdhist = '-F'
hs.args.cdhist  = ''
hs.args.gitlog  = '--filter-only'
share.fuzzyfinder = hs
```
example 4.設定なしの場合
最低限 fzf(あれば)/peco …

feat: fuzzy finder extension integration(catalog)

---

internal/nodos/lookpath.go
internal/nodos/lookpath_unix.go
internal/nodos/lookpath_windows.go

最近、 `wezterm + nyagos` を Windows と Linux 共用で使ってます。
ubuntu で lua の `nyagos.which('cp')` がうまくいかないので発見しました。

linux で which したときに常に見つからない問題を修正しました
