nyaosorg/nyagos

main/lua.go, main/lua_cmd.go
このプルリクをmergeしてもらいたい というわけでなく
ウィンドウの幅など取得できたら
右プロンプトの表示などに使えるかな？と思ったので提案です。
=> Implement nyagos.getviewwidth

commands/ls/ls.go
`ls -l` のファイルサイズの幅をディレクトリごとに計算するようにしてみました。
=> ls: calculate width of file size field for each directory

commands/copy.go, commands/del.go, commands/mkdir.go
NYAGOS は破壊的な操作をする時に確認してくれる親切設計ですが、それが必要ない時もあるので確認しないようにするオプションを追加しました。
`commands/copy.go` はコピペするのが面倒だったので処理をまとめました。
=> Add suppression options

interpreter/interpreter.go
Now, the new feature is disabled to merge master branch.
=> Amp2newconsole

Doc/nyagos_en.md, Doc/nyagos_ja.md
削除された nyagos.echo がドキュメントに残っていたので修正しました。
=> Fix document

appveyor.yml
リリース待ちきれない、けど毎回ビルドするのは大変なので [AppVeyor](https://www.appveyor.com/) の設定ファイルを書いてみました。
AppVeyor でプロジェクトを作ってくださると幸いです。
[![Build status](https://ci.appveyor.com/api/projects/status/1cgltnyya4lqu33b?svg=true)](https://ci.appveyor.com/project/hami-jp/nyagos)
=> [add] add Appveyor configuration file.

appveyor.yml
時間帯変えてビルドしてみましたが、これで安定しました。よろしくお願いします。
=> [change] change the provider of Lua binary.

nyagos.d/catalog/autocd.lua, nyagos.d/catalog/autols.lua
NYAOS 3.xでは含まれていたので
argsfilterとaliasの連携の確認で作ってみただけ
(`autocd.lua`と`nyagos.alias.cd`)
=> Add autocd.lua, autols.lua

nyagos.d/catalog/git.lua
gitの機能をまとめる(に向く)、カタログスクリプトです。
gitの補完のほか、ブランチリスト取得関数を定義しています
なぜかshare.git.branchが関数として利用できていませんが...
前出のpull-reqの関数補完を利用しています
=> Git completion

readline/constants.go
This is related to issue #242.
This patch adds definitions for Alt+Backspace and Alt+"/".
=> Support key combination for Alt+Backspace and Alt+"/".

mains/complete_lua.go
Let me propose a new property to the argument of `completion_hook` and support of an additional return value of `completion_hook`.
The following is the usage:
```lua
nyagos.completion_hook = function(c)
local shownlist = {}
for i = 1, #c.list do
local stat = nyagos.stat(c.list[i])
if stat and stat.isdir then
-- c.shownlist is a new property.
table.insert(shownlist, "\x1b[34;1m" .. c.shownlist[i] .. "\x1b[0m")
else
table.insert(shownlist, c.shownlist[i])
end
end
-- We can return 2 values.
-- The first one is InsertStr, the second one is ListupStr.
return c.list, shownlist
end
```
This example colorize directories in completion.
Here are other points of this patch.
* This patch does not corrupt compatibility of `completion_hook`.  
i.e. Users do not have to change the current …
=> Add shownlist to pass ListupStr to completion_hook.

readline/constants.go, readline/keyfunc.go, readline/readline.go
Skip toggling of CURSOR_ON/CURSOR_OFF to keep the current position of scroll bar when KeyFuncPass is called.
This fixes issue #251.
=> Skip toggling of CURSOR_ON/CURSOR_OFF when KeyFuncPass is called.

mains/io.go
#330 の修正は不完全だったようですので、さらに以下の点を修正しました。
- フォーマットが数値の場合に、読み取り中に EOF に達した場合、エラーとなり読み取った結果が返らない
- フォーマットが数値の場合に、EOF において読み込みを行った場合、`nil` のかわりにエラーが返る
- フォーマットが `*n` の場合に、読み取り結果が数値でなかった場合、`nil` のかわりに `nil` とエラーが返る
- フォーマットが `*a` の場合に、EOF において読み込みを行った場合、空文字列のかわりにエラーが返る
- エラーの場合、戻り値ではなく、`L.ArgError` または `L.RaiseError` を使用するように変更した
まだ、完全でないかもしれませんが、問題なければ取り込んで頂けますか？
=> Fix Lua's file:read compatibility

Doc/07-LuaFunctions_en.md, Doc/07-LuaFunctions_ja.md
=> fix: Doc/07-LuaFunctions_*.md small style problem.

Doc/07-LuaFunctions_ja.md
Doc//07-LuaFunctions_ja.md: fix style again
Oops, I lost other style problem...
=> fix: Doc/07-LuaFunctions_*.md small style problem again.

Doc/07-LuaFunctions_en.md, Doc/07-LuaFunctions_ja.md, Doc/release_note_en.md, Doc/release_note_ja.md, mains/argsfilter.go, mains/commandnotfound.go, mains/functions.go, mains/io.go, mains/lua.go, mains/prompt.go, shell/interpreter.go
=> PR for Issue379

nyagos.d/catalog/subcomplete.lua
GitHub CLI(gh) command rule add.
=> feat: add gh first level subcommand rule

Doc/09-Build_en.md, Doc/09-Build_ja.md
Fix small syntax problem and update go version according to go.mod file.
=> fix: Doc/09-Build_*.md small style problem and go version.

nyagos.d/catalog/subcomplete.lua
=> Add scoop subcommand completion

nyagos.d/catalog/subcomplete.lua
This PR
- add choco/chocolatey command completion
(wait for previous PR :-)
=> feat: add subcompletion choco/chocolaty

Doc/09-Build_en.md, Doc/09-Build_ja.md
=> Fix how to build in document

nyagos.d/catalog/git.lua
git.lua update
- support branch subcommand
- support switch subcommand
- export commit history function
---
処理の作りの良し悪しを含め、PRにて相談したいです
=> feature: git.lua: treat to git v2.33.1 commands

docs/history-4.0_en.md, docs/history-4.1_en.md, docs/history-4.2_en.md, docs/history-4.3_en.md, docs/release_note_en.md, readme_ja.md
The links in some documents were broken, so I fixed the URLs.
I hope you will let me know if there are any problems. Thank you very much!
=> Fix:  links in the documentation.

nyagos.d/catalog/subcomplete.lua
subcomplete.lua update:
* refactor `update_cache()` function/split to specific sub function
* fix: `save_subcommands_cache()` create uniq list(remove duplication)
---
機能追加したり、修正したりするにあたって、まず内容をちょっと整理しました。
=> fix and refactor: subcomplete update

nyagos.d/catalog/subcomplete.lua
Add new feature in subcomplete.lua
Add curl option completion, see below
Curl is native included cli command in Windows, it is useful.
=> feature: Add curl option completion
